version: '3'

networks: 
    laravel:
        driver: bridge

services: 
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        tty: true
        ports:
            - "8002:8001"
        volumes: 
            - ./src:/var/www/app
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - php
            - mysql
        networks: 
            - laravel

    mysql:
        image: mysql
        restart: unless-stopped
        tty: true
        ports: 
            - "4306:3306"
        expose:
            - "3306"
        volumes: 
            - ./mysql:/var/lib/mysql
        environment: 
            MYSQL_DATABASE: laravel_docker
            MYSQL_USER: user
            MYSQL_PASSWORD: user
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks: 
            - laravel
        command: --authentication-policy=mysql_native_password

    php:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        tty: true
        working_dir: /var/www/app
        volumes: 
            - ./src:/var/www/app
        ports: 
            - "9000:9000"
        networks: 
            - laravel

    react:
        build:
            context: .
            dockerfile: DockerfileReact
        restart: unless-stopped
        tty: true
        ports: 
            - "81:3000"
        networks: 
            - laravel