name: Code Check

on:
  - push
  
defaults:
 run:
  working-directory: ./src

jobs:
  prettier:
    name: Run Prettier Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run format:check
